In [14]:
from PolishSystem.OperatorsBasedOnSimilarities.similarities_utils import gian_load_all_pickled_objects
from PolishSystem.read_data import get_cluster_info_file_name, read_cluster_info_file

# vector_size = 20
# clustering_method = "qmc"
# data_folder = r"C:\Users\gac8\PycharmProjects\PSSearch\data\retail_forecasting"
# 
# cluster_info_path = get_cluster_info_file_name(vector_size = vector_size,
#                                                clustering_method = clustering_method,
#                                                data_folder=data_folder)


contents_of_pickle = gian_load_all_pickled_objects(r"C:\Users\gac8\PycharmProjects\PSSearch\retail_forecasting_data_collection\data\cluster_info_250_random.pkl")
which_cluster, centers_embeddings, similarities, a, b, c = contents_of_pickle

In [24]:
import json
from collections import defaultdict
import numpy as np

which_cluster

by_cluster = defaultdict(list)
for index, cluster in enumerate(which_cluster):
    by_cluster[int(cluster)].append(index)
    
print(by_cluster[0])


destination = r"C:\Users\gac8\PycharmProjects\ECXAI-2025-Stirling\pattern_analysis\cluster_items.json"
with open(destination, "w") as file:
    json.dump(by_cluster, file)

[932, 1289, 1314, 2613, 2760, 3408, 3458, 3462, 3478, 3790, 4010, 4118, 4174, 4472, 4513, 6463, 7134, 9003, 9022, 12084, 12338, 12644, 12732, 15120, 17118, 18948, 19552, 19805, 19881, 22265, 22438, 22505, 23532, 23551, 23563, 23804, 23920, 23931, 24135, 24594, 25186, 26071, 26206, 26342, 26348, 26364, 26385, 26419, 26420, 26496, 26560, 26792, 26971, 26977, 26978, 27285, 28107, 28203, 28456, 28682, 28893, 29112, 29114, 29134, 29382, 29549, 30163, 30165, 30168, 30169, 30170, 31226, 31230, 31241, 31737, 32366, 32743, 33338, 33501, 34390, 34868, 35133, 35167, 35332, 35367, 35509, 35989, 35991, 36544, 36556, 36558, 36562, 36564, 36605, 36982, 36983, 37287, 37325, 37331, 37355, 37397, 37519, 37622, 37707, 38159, 38162, 38183, 38190, 38273, 38488, 38497, 38620, 38622, 38626, 38627, 38629, 38631, 38634, 38637, 38640, 38641, 38642, 38643, 38644, 38645, 38646, 38650, 38651, 38652, 38653, 38840, 38844, 38845, 38846, 38896, 38964, 39226, 39230, 39276, 39277, 39278, 39279, 39282, 39284, 39285, 3928

In [5]:
centers_embeddings

array([[-0.7124506 , -0.08883093,  0.53846043, ..., -0.04569619,
         0.68535763, -0.12993132],
       [-0.19162379,  0.24723913, -0.00777762, ..., -0.09810517,
         0.5909923 , -0.6952973 ],
       [ 0.8373225 ,  2.0144207 , -2.1114507 , ..., -2.5232084 ,
         0.79400474, -0.24150321],
       ...,
       [ 0.5759777 ,  0.48961288,  0.453862  , ..., -0.3126783 ,
        -0.64912677,  0.83876103],
       [ 0.23858789, -0.5586763 , -0.17596936, ..., -0.5601218 ,
        -0.4475008 ,  0.39768082],
       [-0.7309567 ,  0.25903696,  0.6369512 , ...,  0.61614996,
        -0.6582785 ,  1.0276165 ]], dtype=float32)

In [6]:
similarities

array([[ 8.9082966e+00,  5.1732750e+00, -1.7701929e+00, ...,
         3.5460621e-01,  6.1005369e-02, -1.5100896e+00],
       [ 5.1732750e+00,  1.0008752e+01, -2.4880695e-01, ...,
         4.0134072e-02,  1.4698497e+00, -1.9082764e+00],
       [-1.7701929e+00, -2.4880695e-01,  6.3589901e+01, ...,
         2.1884444e+00, -2.2572596e+00, -2.7628410e+00],
       ...,
       [ 3.5460621e-01,  4.0134072e-02,  2.1884444e+00, ...,
         1.4098125e+01,  1.4301664e+00,  2.5590990e+00],
       [ 6.1005369e-02,  1.4698497e+00, -2.2572596e+00, ...,
         1.4301664e+00,  7.7089896e+00,  1.6371756e+00],
       [-1.5100896e+00, -1.9082764e+00, -2.7628410e+00, ...,
         2.5590990e+00,  1.6371756e+00,  1.7965137e+01]], dtype=float32)

In [9]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [10]:
b

array([[ 0.30395436, -0.8321151 , -0.2931683 , ..., -0.57997847,
        -0.7250952 , -0.6453552 ],
       [-0.14272776,  0.11352171, -0.05344176, ...,  0.08984439,
        -0.04641999,  0.00352615],
       [ 0.2833685 , -1.0531805 , -0.24265997, ..., -0.08594255,
        -0.7606447 , -0.77974635],
       ...,
       [ 0.15000042, -0.3669556 , -0.63455695, ...,  0.07796335,
         0.22542028, -0.7010793 ],
       [-0.29527092,  0.3422919 , -1.291553  , ..., -0.674535  ,
         0.22947155, -0.5015661 ],
       [-0.74111557, -0.34803483,  0.20126513, ..., -0.04000022,
         0.05895089,  0.03756938]], dtype=float32)

In [11]:
c

array([[ 9.803184  ,  0.15885451,  5.300902  , ...,  1.7908844 ,
         4.1635    , -0.4106587 ],
       [ 0.15885451,  0.7681744 ,  0.11104842, ...,  0.42384315,
        -0.02115219,  0.26430336],
       [ 5.300902  ,  0.11104842, 13.874252  , ...,  2.7215543 ,
         2.7255793 ,  0.09161925],
       ...,
       [ 1.7908844 ,  0.42384315,  2.7215543 , ...,  8.834018  ,
         0.94405967, -0.31263623],
       [ 4.1635    , -0.02115219,  2.7255793 , ...,  0.94405967,
        18.802725  , -1.3536814 ],
       [-0.4106587 ,  0.26430336,  0.09161925, ..., -0.31263623,
        -1.3536814 ,  5.3112884 ]], dtype=float32)