In [1]:
from PolishSystem.OperatorsBasedOnSimilarities.get_operators import get_operators_for_similarities
import os
from PolishSystem.OperatorsBasedOnSimilarities.similarities_utils import gian_get_similarities
from PolishSystem.GlobalPSPolishSearch import find_ps_in_polish_problem
from initial_testing.rearrange_linkage_table import clean_table
from PolishSystem.read_data import get_pRef_from_vectors, get_vectors_file_name, get_fitness_file_name
from Core.PS import PS
from SimplifiedSystem.ps_search_utils import get_metric_function
from Core.PSMetric.Simplicity import Simplicity


# this section will generate the search objectives
size = 20
method = "qmc"
fitness_column_to_use = 2
data_folder = r"C:\Users\gac8\PycharmProjects\PSSearch\data\retail_forecasting"

pRef = get_pRef_from_vectors(get_vectors_file_name(data_folder, size, method), 
                                     get_fitness_file_name(data_folder, size, method), fitness_column_to_use)
best_solution = pRef.get_best_solution()

simplicity = get_metric_function("simplicity")
mean_fitness = get_metric_function("mean_fitness", pRef=pRef)

cluster_info_file_name = os.path.join(data_folder, f"cluster_info_{size}_qmc.pkl")
similarities = gian_get_similarities(cluster_info_file_name)

sampler, mutation, crossover= get_operators_for_similarities(similarities, pRef, mutation_rate=0.05)

crossover.transition_matrix

pss = find_ps_in_polish_problem(original_problem_search_space=pRef.search_space,
                          objectives=[simplicity, mean_fitness],
                          ps_budget=1000,
                          sampling_operator=sampler,
                          mutation_operator=mutation,
                          crossover_operator=crossover,
                          verbose=True
                          )



n_gen  |  n_eval  | n_nds  |     cv_min    |     cv_avg    |      eps      |   indicator  
     1 |        1 |      1 |  0.000000E+00 |  0.000000E+00 |             - |             -
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
20
Children has shape [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 

C:\Users\gac8\PycharmProjects\PSSearch\PolishSystem\OperatorsBasedOnSimilarities\similarities_utils.py:61: RuntimeWarning: invalid value encountered in divide
  with_sum_one = vec / np.sum(vec)


AssertionError: Shape is incorrect of crossover impl.

In [ ]:
for ps in pss:
    print(ps)